server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.duncbh: DEBUG
    org.hibernate:SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

#for h2 profile
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:movieLister-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always

    